services:
  ds:
    platform: linux/amd64
    build: ./ds
    container_name: ds
    ports:
      - "1389:1389"
      - "4444:4444"
    volumes:
      - ds-data:/opt/opendj/data
    networks:
      - forgerock-net

  am:
    build: ./am
    container_name: am
    ports:
      - "8080:8080"
    depends_on:
      - ds
    volumes:
      - am-data:/root/openam
    networks:
      - forgerock-net

  ig:
    build: ./ig
    container_name: ig
    ports:
      - "8081:8080"
    extra_hosts:
      - "openam.lloyds.com:host-gateway"
    environment:
      - AM_URL=http://am:8080/openam
      - AGENT_SECRET_ID=aWctYWdlbnQtcGFzc3dvcmQ=
    depends_on:
      - am
    networks:
      - forgerock-net

networks:
  forgerock-net:
    driver: bridge

volumes:
  ds-data:
  am-data:
